In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Load the CSV files

In [2]:
btc = pd.read_csv("BTC_full_data.csv")
eth = pd.read_csv("ETH_full_data.csv")

btc.head()
eth.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Log_Return
0,2018-01-01,755.757019,782.530029,742.004028,772.640991,772.640991,2595760128,NaN
1,2018-01-02,772.346008,914.830017,772.346008,884.443970,884.443970,5783349760,0.135145
2,2018-01-03,886.000000,974.471008,868.450989,962.719971,962.719971,5093159936,0.084803
3,2018-01-04,961.713013,1045.079956,946.085999,980.921997,980.921997,6502859776,0.018730
4,2018-01-05,975.750000,1075.390015,956.325012,997.719971,997.719971,6683149824,0.016980

# 2. evaluation function

In [3]:
def evaluate_strategy(strategy_returns, risk_free_rate=0.03, trading_days=365):
    r = strategy_returns.dropna()

    cumulative = np.exp(r.cumsum())

    cumulative_pnl = cumulative.iloc[-1] - 1
    avg_daily_pnl = r.mean()
    daily_vol = r.std() 
    annual_return = r.mean() * trading_days
    annual_vol = r.std() * np.sqrt(trading_days)

    sharpe = (annual_return - risk_free_rate) / annual_vol if annual_vol != 0 else np.nan

    peak = cumulative.cummax()
    drawdown = (cumulative - peak) / peak
    max_dd = drawdown.min()

    return {
        "Cumulative PnL": cumulative_pnl,
        "Average Daily PnL": avg_daily_pnl,
        "Daily Volatility": daily_vol, 
        "Annualised Return": annual_return,
        "Volatility": annual_vol,
        "Sharpe Ratio": sharpe,
        "Max Drawdown": max_dd
    }

# 3. Define Bollinger Band (price level)
position = 1 → long when price is below lower band
position = -1 → short when price is above upper band
position = 0 → exit when price reverts to the rolling mean

In [4]:
def bollinger_price_csv(
    df,
    output_file,
    date_col="Date",
    price_col="Close",
    window=20,
    num_std=2
):

    df = df.copy()

    # format date
    df[date_col] = pd.to_datetime(df[date_col])
    df = df.sort_values(date_col).reset_index(drop=True)

    # price + log return
    df["price"] = df[price_col]
    df["log_return"] = np.log(df["price"] / df["price"].shift(1))
    df["log_return"] = df["log_return"].fillna(0)

    # Bollinger stats
    df["rolling_mean"] = df["price"].rolling(window).mean()
    df["rolling_std"] = df["price"].rolling(window).std()

    df["upper_band"] = df["rolling_mean"] + num_std * df["rolling_std"]
    df["lower_band"] = df["rolling_mean"] - num_std * df["rolling_std"]

    position = 0
    positions = []
    trades = []
    actions = []

    for i in range(len(df)):

        price = df.loc[i, "price"]
        mean = df.loc[i, "rolling_mean"]
        upper = df.loc[i, "upper_band"]
        lower = df.loc[i, "lower_band"]

        signal = 0
        action = "hold"

        if pd.isna(mean):
            position = 0

        elif position == 0:
            if price < lower:
                position = 1
                signal = 1
                action = "buy"

            elif price > upper:
                position = -1
                signal = -1
                action = "sell"

        elif position == 1:
            if price >= mean:
                position = 0
                signal = -1
                action = "sell"

        elif position == -1:
            if price <= mean:
                position = 0
                signal = 1
                action = "buy"

        positions.append(position)
        trades.append(signal)
        actions.append(action)

    df["trade"] = trades
    df["trade_action"] = actions
    df["position"] = positions
    out = df[[date_col, "price", "log_return", "trade", "trade_action", "position"]]
    out = out.rename(columns={date_col: "date"})

    # save csv
    out.to_csv(output_file, index=False)

    print(f"CSV exported → {output_file}")

    return out

# 4. Run strategy and create final metrics table

In [5]:
btc_bb = bollinger_price_csv(btc, "btc_bollinger_post_trade.csv")
eth_bb = bollinger_price_csv(eth, "eth_bollinger_post_trade.csv")

# Compute strategy returns: position is lagged by 1 to avoid look-ahead bias
btc_bb["strategy_return"] = btc_bb["position"].shift(1) * btc_bb["log_return"]
eth_bb["strategy_return"] = eth_bb["position"].shift(1) * eth_bb["log_return"]

# Evaluate both
btc_metrics = evaluate_strategy(btc_bb["strategy_return"])
eth_metrics = evaluate_strategy(eth_bb["strategy_return"])

# Post-trade tables: rows where a trade occurred
btc_trades = btc_bb[btc_bb["trade"] != 0].copy()
eth_trades = eth_bb[eth_bb["trade"] != 0].copy()

print("=== BTC Post-Trade Table ===")
print(btc_trades.to_string(index=False))
print(f"\nTotal BTC trades: {len(btc_trades)}")

print("\n=== ETH Post-Trade Table ===")
print(eth_trades.to_string(index=False))
print(f"\nTotal ETH trades: {len(eth_trades)}")

CSV exported → btc_bollinger_post_trade.csv
CSV exported → eth_bollinger_post_trade.csv
=== BTC Post-Trade Table ===
      date         price  log_return  trade trade_action  position  strategy_return
2018-02-02   8830.750000   -0.037756      1          buy         1        -0.000000
2018-02-14   9494.629883    0.099161     -1         sell         0         0.099161
2018-03-10   8866.000000   -0.051820      1          buy         1        -0.000000
2018-04-12   7889.250000    0.124127     -1         sell         0         0.124127
2018-04-15   8329.110352    0.042037     -1         sell        -1         0.000000
2018-05-10   9043.940430   -0.030623      1          buy         0         0.030623
2018-05-11   8441.490234   -0.068936      1          buy         1        -0.000000
2018-06-07   7678.240234    0.003165     -1         sell         0         0.003165
2018-06-10   6786.020020   -0.104293      1          buy         1        -0.000000
2018-07-02   6614.180176    0.035136     -1         sell         0         0.035136
2018-07-17   7321.040039    0.082433     -1         sell        -1         0.000000
2018-08-02   7567.149902   -0.007604      1          buy         0         0.007604
2018-08-08   6305.799805   -0.068535      1          buy         1        -0.000000
2018-08-23   6534.879883    0.024502     -1         sell         0         0.024502
2018-08-27   6884.640137    0.026102     -1         sell        -1         0.000000
2018-09-05   6792.830078   -0.080418      1          buy         0         0.080418
2018-10-11   6256.240234   -0.051295      1          buy         1        -0.000000
2018-10-15   6596.540039    0.047436     -1         sell         0         0.047436
2018-11-14   5738.350098   -0.102776      1          buy         1        -0.000000
2018-12-18   3696.059082    0.041485     -1         sell         0         0.041485
2019-01-29   3448.116943   -0.006456      1          buy         1        -0.000000
2019-02-08   3666.780273    0.075694     -1         sell         0         0.075694
2019-02-18   3915.714355    0.063761     -1         sell        -1         0.000000
2019-03-04   3761.557129   -0.022506      1          buy         0         0.022506
2019-03-16   4048.725830    0.021928     -1         sell        -1         0.000000
2019-03-25   3963.070557   -0.014802      1          buy         0         0.014802
2019-04-02   4879.877930    0.160042     -1         sell        -1         0.000000
2019-04-25   5210.515625   -0.047661      1          buy         0         0.047661
2019-05-03   5768.289551    0.046667     -1         sell        -1         0.000000
2019-06-04   7707.770996   -0.063001      1          buy         0         0.063001
2019-06-17   9320.352539    0.035588     -1         sell        -1         0.000000
2019-07-11  11358.662109   -0.067884      1          buy         0         0.067884
2019-07-16   9477.641602   -0.139377      1          buy         1        -0.000000
2019-08-01  10399.668945    0.030663     -1         sell         0         0.030663
2019-08-05  11805.653320    0.073397     -1         sell        -1         0.000000
2019-08-14  10051.704102   -0.080638      1          buy         0         0.080638
2019-09-23   9729.324219   -0.034455      1          buy         1        -0.000000
2019-10-10   8586.473633   -0.001079     -1         sell         0        -0.001079
2019-10-23   7514.671875   -0.072312      1          buy         1        -0.000000
2019-10-25   8660.700195    0.144761     -1         sell         0         0.144761
2019-10-26   9244.972656    0.065284     -1         sell        -1         0.000000
2019-11-08   8804.880859   -0.051214      1          buy         0         0.051214
2019-11-15   8491.992188   -0.025129      1          buy         1        -0.000000
2019-12-07   7556.237793    0.001224     -1         sell         0         0.001224
2019-12-16   6932.480469   -0.031217      1          buy         1        -0.000000
2019-12-22   7511.588867    0.043595     -1         sell         0         0.043595
2020-01-06   7769.219238    0.047161     -1         sell        -1         0.000000
2020-01-25   8367.847656   -0.009229      1          buy         0         0.009229
2020-01-28   9358.589844    0.049141     -1         sell        -1         0.000000
2020-02-17   9690.142578   -0.024898      1          buy         0         0.024898
2020-02-25   9341.705078   -0.032487      1          buy         1        -0.000000
2020-03-24   6734.803711    0.048445     -1         sell         0         0.048445
2020-04-29   8801.038086    0.119841     -1         sell        -1         0.000000
2020-05-21   9081.761719   -0.047440      1          buy         0         0.047440
2020-06-01  10167.268555    0.071989     -1         sell        -1         0.000000
2020-06-11   9321.781250   -0.057156      1          buy         0         0.057156
2020-07-22   9525.363281    0.015923     -1         sell        -1         0.000000
2020-08-21  11592.489258   -0.024362      1          buy         0         0.024362
2020-09-03  10245.296875   -0.108025      1          buy         1        -0.000000
2020-09-16  10974.905273    0.016348     -1         sell         0         0.016348
2020-10-09  11064.458008    0.013537     -1         sell        -1         0.000000
2020-11-27  17108.402344   -0.002465      1          buy         0         0.002465
2020-12-16  21310.597656    0.093052     -1         sell        -1         0.000000
2021-01-20  35547.750000   -0.014579      1          buy         0         0.014579
2021-02-08  46196.464844    0.171821     -1         sell        -1         0.000000
2021-02-25  47093.851562   -0.053970      1          buy         0         0.053970
2021-03-13  61243.085938    0.065990     -1         sell        -1         0.000000
2021-03-22  54529.144531   -0.053457      1          buy         0         0.053457
2021-04-13  63503.457031    0.058527     -1         sell        -1         0.000000
2021-04-18  56216.183594   -0.076472      1          buy         0         0.076472
2021-04-22  51762.273438   -0.040582      1          buy         1        -0.000000
2021-04-30  57750.175781    0.075415     -1         sell         0         0.075415
2021-05-15  46760.187500   -0.064599      1          buy         1        -0.000000
2021-06-03  39208.765625    0.042557     -1         sell         0         0.042557
2021-06-21  31676.693359   -0.119522      1          buy         1        -0.000000
2021-06-29  35867.777344    0.040785     -1         sell         0         0.040785
2021-07-16  31421.539062   -0.011367      1          buy         1        -0.000000
2021-07-23  33581.550781    0.038504     -1         sell         0         0.038504
2021-07-26  37337.535156    0.054695     -1         sell        -1         0.000000
2021-08-30  47054.984375   -0.037025      1          buy         0         0.037025
2021-09-06  52633.535156    0.016863     -1         sell        -1         0.000000
2021-09-07  46811.128906   -0.117232      1          buy         0         0.117232
2021-09-21  40693.675781   -0.051488      1          buy         1        -0.000000
2021-10-01  48116.941406    0.094208     -1         sell         0         0.094208
2021-10-06  55361.449219    0.072014     -1         sell        -1         0.000000
2021-10-27  58482.386719   -0.031664      1          buy         0         0.031664
2021-11-08  67566.828125    0.064806     -1         sell        -1         0.000000
2021-11-16  60161.246094   -0.054922      1          buy         0         0.054922
2021-11-18  56942.136719   -0.058424      1          buy         1        -0.000000
2021-12-22  48628.511719   -0.006316     -1         sell         0        -0.006316
2022-01-05  43569.003906   -0.052066      1          buy         1        -0.000000
2022-02-04  41500.875000    0.110627     -1         sell         0         0.110627
2022-02-07  43840.285156    0.033112     -1         sell        -1         0.000000
2022-02-17  40538.011719   -0.081082      1          buy         0         0.081082
2022-03-24  43960.933594    0.024594     -1         sell        -1         0.000000
2022-04-06  43206.738281   -0.052946      1          buy         0         0.052946
2022-04-11  39521.902344   -0.065747      1          buy         1        -0.000000
2022-05-04  39698.371094    0.050313     -1         sell         0         0.050313
2022-05-05  36575.140625   -0.081941      1          buy         1        -0.000000
2022-05-30  31726.390625    0.074592     -1         sell         0         0.074592
2022-05-31  31792.310547    0.002076     -1         sell        -1         0.000000
2022-06-01  29799.080078   -0.064747      1          buy         0         0.064747
2022-06-12  26762.648438   -0.058001      1          buy         1        -0.000000
2022-07-06  20548.246094    0.017582     -1         sell         0         0.017582
2022-07-18  22485.689453    0.078920     -1         sell        -1         0.000000
2022-07-25  21361.701172   -0.056756      1          buy         0         0.056756
2022-08-19  20877.552734   -0.106027      1          buy         1        -0.000000
2022-09-09  21381.152344    0.100860     -1         sell         0         0.100860
2022-09-12  22370.449219    0.027242     -1         sell        -1         0.000000
2022-09-13  20296.707031   -0.097282      1          buy         0         0.097282
2022-10-04  20336.843750    0.035702     -1         sell        -1         0.000000
2022-10-10  19141.484375   -0.015805      1          buy         0         0.015805
2022-10-25  20095.857422    0.038050     -1         sell        -1         0.000000
2022-11-08  18541.271484   -0.105429      1          buy         0         0.105429
2022-11-09  15880.780273   -0.154890      1          buy         1        -0.000000
2022-11-30  17168.566406    0.043060     -1         sell         0         0.043060
2022-12-13  17781.318359    0.032865     -1         sell        -1         0.000000
2022-12-16  16647.484375   -0.042190      1          buy         0         0.042190
2023-01-08  17091.144531    0.007993     -1         sell        -1         0.000000
2023-02-06  22760.109375   -0.008555      1          buy         0         0.008555
2023-02-09  21819.039062   -0.050073      1          buy         1        -0.000000
2023-02-15  24307.841797    0.089770     -1         sell         0         0.089770
2023-03-09  20363.021484   -0.064425      1          buy         1        -0.000000
2023-03-13  24197.533203    0.087784     -1         sell         0         0.087784
2023-03-17  27423.929688    0.090431     -1         sell        -1         0.000000
2023-04-07  27925.859375   -0.004227      1          buy         0         0.004227
2023-04-10  29652.980469    0.045534     -1         sell        -1         0.000000
2023-04-19  28822.679688   -0.053200      1          buy         0         0.053200
2023-05-28  28085.646484    0.044309     -1         sell        -1         0.000000
2023-06-01  26819.972656   -0.014793      1          buy         0         0.014793
2023-06-05  25760.097656   -0.051410      1          buy         1        -0.000000
2023-06-06  27238.783203    0.055815     -1         sell         0         0.055815
2023-06-14  25124.675781   -0.031115      1          buy         1        -0.000000
2023-06-19  26851.029297    0.019359     -1         sell         0         0.019359
2023-06-20  28327.488281    0.053528     -1         sell        -1         0.000000
2023-07-09  30171.234375   -0.004013      1          buy         0         0.004013
2023-07-13  31476.048828    0.035059     -1         sell        -1         0.000000
2023-07-14  30334.068359   -0.036955      1          buy         0         0.036955
2023-07-24  29176.916016   -0.030634      1          buy         1        -0.000000
2023-08-08  29765.492188    0.019846     -1         sell         0         0.019846
2023-08-16  28701.779297   -0.016194      1          buy         1        -0.000000
2023-08-29  27727.392578    0.060250     -1         sell         0         0.060250
2023-09-19  27211.117188    0.016931     -1         sell        -1         0.000000
2023-09-24  26256.826172   -0.012210      1          buy         0         0.012210
2023-10-01  27983.750000    0.036976     -1         sell        -1         0.000000
2023-10-11  26873.320312   -0.019081      1          buy         0         0.019081
2023-10-16  28519.466797    0.048854     -1         sell        -1         0.000000
2023-11-21  35813.812500   -0.045393      1          buy         0         0.045393
2023-12-02  39476.332031    0.020152     -1         sell        -1         0.000000
2023-12-17  41364.664062   -0.020943      1          buy         0         0.020943
2024-01-02  44957.968750    0.017743     -1         sell        -1         0.000000
2024-01-03  42848.175781   -0.048065      1          buy         0         0.048065
2024-01-08  46970.503906    0.066624     -1         sell        -1         0.000000
2024-01-12  42853.167969   -0.078843      1          buy         0         0.078843
2024-02-08  45301.566406    0.021946     -1         sell        -1         0.000000
2024-03-16  65315.117188   -0.060718      1          buy         0         0.060718
2024-04-13  63821.472656   -0.051522      1          buy         1        -0.000000
2024-04-22  66837.679688    0.029009     -1         sell         0         0.029009
2024-05-01  58254.011719   -0.040090      1          buy         1        -0.000000
2024-05-04  63891.472656    0.015801     -1         sell         0         0.015801
2024-05-15  66267.492188    0.073804     -1         sell        -1         0.000000
2024-06-11  67332.031250   -0.031867      1          buy         0         0.031867
2024-06-24  60277.414062   -0.047043      1          buy         1        -0.000000
2024-07-14  60787.792969    0.025928     -1         sell         0         0.025928
2024-07-15  64870.152344    0.064999     -1         sell        -1         0.000000
2024-07-31  64619.250000   -0.024183      1          buy         0         0.024183
2024-08-02  61415.066406   -0.062217      1          buy         1        -0.000000
2024-08-21  61175.191406    0.035987     -1         sell         0         0.035987
2024-08-23  64094.355469    0.059667     -1         sell        -1         0.000000
2024-08-27  59504.132812   -0.055193      1          buy         0         0.055193
2024-09-06  53948.753906   -0.040179      1          buy         1        -0.000000
2024-09-13  60571.300781    0.041191     -1         sell         0         0.041191
2024-09-19  62940.457031    0.020721     -1         sell        -1         0.000000
2024-10-01  60837.007812   -0.040153      1          buy         0         0.040153
2024-10-29  72720.492188    0.039447     -1         sell        -1         0.000000
2024-11-04  67811.507812   -0.013616      1          buy         0         0.013616
2024-11-06  75639.078125    0.086669     -1         sell        -1         0.000000
2024-12-10  96675.429688   -0.007803      1          buy         0         0.007803
2024-12-15 104298.695312    0.028452     -1         sell        -1         0.000000
2024-12-19  97490.953125   -0.025826      1          buy         0         0.025826
2025-01-06 102078.085938    0.037562     -1         sell        -1         0.000000
2025-01-08  95043.523438   -0.019579      1          buy         0         0.019579
2025-01-17 104462.039062    0.046087     -1         sell        -1         0.000000
2025-02-01 100655.906250   -0.017228      1          buy         0         0.017228
2025-02-05  96615.445312   -0.012920      1          buy         1        -0.000000
2025-02-20  98333.937500    0.017422     -1         sell         0         0.017422
2025-02-24  91418.171875   -0.051753      1          buy         1        -0.000000
2025-03-02  94248.351562    0.091215     -1         sell         0         0.091215
2025-04-06  78214.484375   -0.065449      1          buy         1        -0.000000
2025-04-11  83404.835938    0.046364     -1         sell         0         0.046364
2025-04-22  93441.890625    0.065485     -1         sell        -1         0.000000
2025-05-29 105641.757812   -0.020246      1          buy         0         0.020246
2025-06-05 101575.953125   -0.030598      1          buy         1        -0.000000
2025-06-09 110294.101562    0.041660     -1         sell         0         0.041660
2025-07-10 115987.203125    0.041012     -1         sell        -1         0.000000
2025-07-29 117922.148438   -0.000020      1          buy         0         0.000020
2025-07-31 115758.203125   -0.017749      1          buy         1        -0.000000
2025-08-07 117496.898438    0.021236     -1         sell         0         0.021236
2025-08-13 123344.062500    0.026046     -1         sell        -1         0.000000
2025-08-18 116252.312500   -0.010276      1          buy         0         0.010276
2025-08-25 110124.351562   -0.029826      1          buy         1        -0.000000
2025-09-08 112071.429688    0.008097     -1         sell         0         0.008097
2025-09-11 115507.539062    0.013529     -1         sell        -1         0.000000
2025-09-22 112748.507812   -0.022431      1          buy         0         0.022431
2025-09-25 109049.289062   -0.038492      1          buy         1        -0.000000
2025-09-29 114400.382812    0.020111     -1         sell         0         0.020111
2025-10-02 120681.257812    0.016984     -1         sell        -1         0.000000
2025-10-10 113214.367188   -0.072322      1          buy         0         0.072322
2025-11-04 101590.523438   -0.047641      1          buy         1        -0.000000
2025-12-02  91350.203125    0.056621     -1         sell         0         0.056621
2025-12-15  86419.781250   -0.020109      1          buy         1        -0.000000
2025-12-30  88430.132812    0.014718     -1         sell         0         0.014718

Total BTC trades: 212

=== ETH Post-Trade Table ===
      date       price  log_return  trade trade_action  position  strategy_return
2018-02-04  834.682007   -0.144060      1          buy         1        -0.000000
2018-02-15  936.976013    0.014421     -1         sell         0         0.014421
2018-03-07  752.830994   -0.081738      1          buy         1        -0.000000
2018-04-11  430.540009    0.038587     -1         sell         0         0.038587
2018-04-15  531.702026    0.058523     -1         sell        -1         0.000000
2018-05-11  679.585999   -0.067824      1          buy         0         0.067824
2018-05-23  583.585022   -0.104301      1          buy         1        -0.000000
2018-06-08  601.077026   -0.006814     -1         sell         0        -0.006814
2018-06-10  526.479004   -0.126647      1          buy         1        -0.000000
2018-07-06  474.011993   -0.000843     -1         sell         0        -0.000843
2018-08-01  420.747009   -0.030706      1          buy         1        -0.000000
2018-08-28  296.498993    0.037441     -1         sell         0         0.037441
2018-09-05  232.330994   -0.206860      1          buy         1        -0.000000
2018-09-21  246.584000    0.093422     -1         sell         0         0.093422
2018-10-11  189.498993   -0.175129      1          buy         1        -0.000000
2018-11-04  207.485992    0.035817     -1         sell         0         0.035817
2018-11-06  218.451996    0.043797     -1         sell        -1         0.000000
2018-11-14  181.397003   -0.131190      1          buy         0         0.131190
2018-11-15  180.806000   -0.003263      1          buy         1        -0.000000
2018-12-18  101.112457    0.060949     -1         sell         0         0.060949
2018-12-23  130.765259    0.113288     -1         sell        -1         0.000000
2019-01-10  128.625183   -0.159072      1          buy         0         0.159072

# 5. Result table

In [6]:
results = pd.DataFrame({
    "Criteria": [
        "Cumulative pnl",
        "Average daily pnl",
        "Annualised return",
        "Max drawdown",
        "Daily volatility", 
        "Volatility",
        "Sharpe Ratio (risk-free rate assumed to be 3%)"
    ],
    "BTC": [
        btc_metrics["Cumulative PnL"],
        btc_metrics["Average Daily PnL"],
        btc_metrics["Annualised Return"],
        btc_metrics["Max Drawdown"],
        btc_metrics["Daily Volatility"],
        btc_metrics["Volatility"],
        btc_metrics["Sharpe Ratio"]
    ],
    "ETH": [
        eth_metrics["Cumulative PnL"],
        eth_metrics["Average Daily PnL"],
        eth_metrics["Annualised Return"],
        eth_metrics["Max Drawdown"],
        eth_metrics["Daily Volatility"],
        eth_metrics["Volatility"],
        eth_metrics["Sharpe Ratio"]
    ]
})

results

                                         Criteria       BTC       ETH
0                                  Cumulative pnl -0.774877 -0.949464
1                               Average daily pnl -0.000511 -0.001022
2                               Annualised return -0.186389 -0.373134
3                                    Max drawdown -0.925013 -0.970129
4                                Daily volatility  0.026886  0.034582
5                                      Volatility  0.513651  0.660685
6  Sharpe Ratio (risk-free rate assumed to be 3%) -0.421276 -0.610176

The Bollinger Bands mean-reversion strategy generated persistently negative performance for both BTC and ETH. Although short-term price reversals occasionally occurred, the strategy was unable to offset the impact of prolonged trending market regimes. This resulted in substantial cumulative losses, large maximum drawdowns exceeding 90%, and negative Sharpe ratios, indicating poor risk-adjusted returns. The weaker performance observed for ETH relative to BTC is consistent with its higher volatility and stronger directional price movements. Overall, the findings suggest that a simple Bollinger-based mean-reversion approach is not well suited to highly volatile and trend-dominated cryptocurrency markets without additional trend-filtering or risk-management mechanisms.